import {
  BadgeCheck,
  BookMarked,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Car,
  ChartNoAxesCombined,
  Cloud,
  CloudSun,
  Code2,
  ExternalLink,
  Github,
  GraduationCap,
  Headphones,
  HeartPulse,
  Home,
  IdCard,
  Landmark,
  Languages,
  LayoutDashboard,
  LibraryBig,
  Link2,
  Linkedin,
  Luggage,
  MapPinned,
  Newspaper,
  NotebookTabs,
  PackageOpen,
  Palette,
  PanelsTopLeft,
  Scale,
  School,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Tag,
  UserRoundSearch,
  UsersRound,
  WalletCards,
  Zap,
} from "lucide-react";

export const iconMap = {
  "badge-check": BadgeCheck,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  "briefcase-business": BriefcaseBusiness,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  car: Car,
  "chart-no-axes-combined": ChartNoAxesCombined,
  cloud: Cloud,
  "cloud-sun": CloudSun,
  "code-2": Code2,
  github: Github,
  "graduation-cap": GraduationCap,
  headphones: Headphones,
  "heart-pulse": HeartPulse,
  home: Home,
  "id-card": IdCard,
  landmark: Landmark,
  languages: Languages,
  "layout-dashboard": LayoutDashboard,
  "library-big": LibraryBig,
  link: Link2,
  linkedin: Linkedin,
  luggage: Luggage,
  "map-pinned": MapPinned,
  newspaper: Newspaper,
  "notebook-tabs": NotebookTabs,
  "package-open": PackageOpen,
  palette: Palette,
  "panels-top-left": PanelsTopLeft,
  scale: Scale,
  school: School,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  tag: Tag,
  "user-round-search": UserRoundSearch,
  "users-round": UsersRound,
  "wallet-cards": WalletCards,
  zap: Zap,
};

export const FallbackIcon = ExternalLink;
